#!/bin/bash
if [[ ${TRAVIS_OS_NAME} = linux ]]; then
# If needed, update the compilers
if [[ ${GCC_NEEDED_VERSION} != "" && ${GCC_PPA} != "" && ${CC} == "gcc" ]]; then
  sudo add-apt-repository -y ppa:${GCC_PPA};
  sudo apt-get update -qq;
  sudo apt-get install -qq ${CC}-${GCC_NEEDED_VERSION} ${CXX}-${GCC_NEEDED_VERSION};
  export CC=${CC}-${GCC_NEEDED_VERSION};
  export CXX=${CXX}-${GCC_NEEDED_VERSION};
elif [[ ${CLANG_NEEDED_VERSION} != "" && ${CLANG_PPA} != "" ]]; then
  sudo add-apt-repository -y ppa:${CLANG_PPA};
  sudo apt-get update -qq;
  sudo apt-get install -qq ${CC}-${CLANG_NEEDED_VERSION};
fi;
fi;
